# Generated by Django 5.2.5 on 2025-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_menu_remove_order_sold_out_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
