# Generated by Django 5.2.5 on 2025-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_menu_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
