# Generated by Django 5.2.5 on 2025-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
