# Generated by Django 5.2.6 on 2025-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('main', '메인'), ('side', '사이드'), ('beverage', '음료'), ('etc', '기타')], default='etc', max_length=20),
        ),
    ]
