# Generated by Django 5.2.5 on 2025-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
